### ISSUE TITLE
Sanitize Input when Saving Templates

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#236]
## Problem

When adding templates to Cyclops, you'll need to enter the `Name`, `Repository URL`, `Path`, and `Version`. If you accidentally include an additional slash (`/`) before or after `Repository URL`, `Path`, or `Version`, Cyclops will still save the template. 

However, this extra slash (`/`) leads to problems later on. When you try to use these templates in the Modules tab, Cyclops won’t be able to fetch them properly. 

### Examples

Adding `/` to the end of repo, or the start of path, or end of path:

```yaml
Repository URL: https://github.com/cyclops-ui/templates/
Path: /demo/
Version: main
```

```json
{
    "message": "Error loading template",
    "description": "could not read 'values.schema.json' file; it should be placed in the repo/path you provided; make sure you provided the correct path"
}
```

Adding `/` to the end of `Version`:

```yaml
Repository URL: https://github.com/cyclops-ui/templates
Path: demo
Version: main/
```

```json
{
    "message":"Error loading template",
    "description":"gzip: invalid header"
}
```

## Solution

Update the `CreateTemplateStore` & `EditTemplatesStore` functions to remove the extra `/` from the start and end of `repo`, `path` and `version` values. The functions can be found in `cyclops-ctrl/internal/controller/templates.go`
