### ISSUE TITLE
`cyctl`:  implement a create method for Modules

### ISSUE THREAD

**Issue by siddhantprateek** [cyclops-ui/cyclops#290]
**Is your feature request related to a problem? Please describe.**
We need to implement a create method for Modules, TemplateStore, TemplateAuthRules custom resource. The command structure should be:

```bash
cyctl create module <module-name> 

required flags:
Need to be discussed...
```

**Would you like to work on this issue?**
Yes

**Comment by siddhantprateek** [comment]
@petar-cvit, I've implemented a command for creating TemplateStore custom resources:

```bash
cyctl create template NAME --repo='https://github.com/cyclops-ui/templates' --path='/path' --version='main'
```

I’m considering adding namespace flags as well.

Currently, the `--version` flag defaults to `main`.

**What are your thoughts on this?**

**Comment by petar-cvit** [comment]
Nice! The version flag does not need to default to anything. There is already logic for defaulting when the version is not specified in the controller, so a template without a version is completely valid.

Can you split this issue into multiple smaller ones since Module creation could be a bigger chunk of work then the creation TemplateStore CR? You can open a new issue for the creation of templates and I can assign you to it

**Comment by siddhantprateek** [comment]
I was wondering if we could have a command like,
```bash
cyctl create module NAME -f values.yaml
```
since the values are not consistent.

**Comment by petar-cvit** [comment]
you are thinking about `values.yaml` containing only the values or the whole Module? If its just the values, you need to add flags for template reference

**Comment by siddhantprateek** [comment]
the values.yaml will contain this
```yaml
  values:
    general:
      environment:
        ENVIRONMENT: production
      image: nginx
      version: 1.14.2
    name: nginx-app
    networking:
      expose: true
      port: 8080
    scaling:
      replicas: 2
      resources:
        cpu: 0.1
        memory: 0.01
```

and the complete command would look something like this
```bash
cyctl create module NAME -f values.yaml \ 
--repo 'github.com/github/demo' \
--path '/path/to/charts' \
--version 'main'
```
