### ISSUE TITLE
Implement UI component for Secrets

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#297]
**Is your feature request related to a problem? Please describe.**
Some K8s components are supported to have a custom UI component, and those can be found [here](https://github.com/cyclops-ui/cyclops/tree/main/cyclops-ui/src/components/k8s-resources). The scope of this issue is to support `Secrets`. The new `Secrets` component should be similar to other components we already have, so feel free to check the existing ones out. You can fetch the data about a secret by calling the backend on

```
/api/resources?group=&version=v1&kind=Secret&name=<name>&namespace=<namespace>
```

To be able to test this, you will need to use a template that supports secrets. You should add the following template and create a Module from it:
```yaml
repo: https://github.com/cyclops-ui/templates
path: redis
version: test-secrets-ui
```
