### ISSUE TITLE
support updating modules using cyctl

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#454]
**Is your feature request related to a problem? Please describe.**
cyctl can currently create, list and delete modules. It would be useful to update modules using cyctl. For the start, cyctl should support updating the `spec.values`.

The command invocation should look like this:
```sh
cyctl update module <module-name> --key=<key> --value=<value>
```

If there is already a deployed module defined like this:
```yaml
apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  name: test
spec:
  template:
    path: path
    repo: repo
    version: version
  values:
    scaling:
      replicas: 2
      cpu: 1
    networking:
      expose: true
```
cyctl should support updating just the number of replicas with the command:
```sh
cyctl update module test --key="scaling.replicas" --value=3
```
