### ISSUE TITLE
Support Helm chart dependecies

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#75]
**Is your feature request related to a problem? Please describe.**
[Helm chart dependencies](https://helm.sh/docs/topics/charts/#chart-dependencies) are often used and need to be supported when creating modules.

**Describe the solution you'd like**
Fetch each dependency and render a UI based on dependency schema from `values.schema.json`. Rendered UI of a dependency will be part of the parent chart UI, but under the name of dependency.

For instance, for dependency:
```
dependencies:
  - name: mysql
    version: "9.3.4"
    repository: "https://charts.bitnami.com/bitnami"
```
UI of the parent chart will have a rendered object that fits the schema fetched from `https://charts.bitnami.com/bitnami`
