### ISSUE TITLE
Deployment Target as part of Template

### ISSUE THREAD

**Issue by DarthBlair** [cyclops-ui/cyclops#837]
**Is your feature request related to a problem? Please describe.**
GitOps IS our Default way to deploy. If WE create new modules WE need to specify the Git Connection every time. Sometimes in a Rush IT IS forgotten.

**Describe the solution you'd like**
The Deploymebt target could be either within the Templates or a seperat object which IS linked to the Template. So AS you choose your Template the target is already defined and Not to be Changed by someone creating a new Module.

**Comment by petar-cvit** [comment]
Hey @DarthBlair, thanks for raising this!

I already have one PR that's a bit outdated, but it should solve what you are describing. With this change, your templates would have an additional `enforceGitOpsWrite` property to define where to push the config of a module created from this template.

```yaml
apiVersion: cyclops-ui.com/v1alpha1
kind: TemplateStore
metadata:
  name: demo
  namespace: cyclops
spec:
  path: demo
  repo: https://github.com/cyclops-ui/templates
  version: main
  sourceType: git
  enforceGitOpsWrite:
    repo: https://github.com/your-org/your-repo
    path: modules
    version: main
```

We also added the templating capabilities so you can push to different repos/paths based on the values provided.

```yaml
enforceGitOpsWrite:
  repo: https://github.com/your-org/your-repo
  path: modules/{{ .meta.namespace }}/{{ .meta.name }}
  version: main
```

Let me know if this would fit your use case, and I can create a release candidate for it shortly.
